classdef McsData
% Read and store the contents of a HDF5 file generated by MCS software.
% 
% Holds a cell array of the recordings present in the file.
%
% Usage:
%
%   Import the McsHDF5 package:
%   
%       import McsHDF5.*
%
%   Read a HDF5 file:
%
%       data = McsData('Name_of_HDF5_file.h5');
%
%   Plot the individual streams contained in the file:
%
%       plot(data,[]);
%
%   See help McsData.plot for more information
%
%   walter@multichannelsystems.com
%   21.02.2014

    properties
        FileName
        McsHdf5Version
        Data
        Recording = {};
    end
    
    methods
        
        function md = McsData(filename)
        % Reads a HDF5 file created by MCS software.
        %
        % function md = McsData(filename)
        %
        % This command will just read the meta-information in the file, the
        % actual data will be read lazily, i.e. once it is needed (e.g.
        % when plot is called).
        %
        % Input:
        %   filename    -   (string) Name of the HDF5 file
        %
        % Output:
        %   md          -   A McsData object
        %
        %   walter@multichannelsystems.com
        %   21.02.2014
            
            inf = h5info(filename);
            md.FileName = inf.Filename;
            md.McsHdf5Version = inf.Attributes.Value;
            
            if md.McsHdf5Version ~= 1
                error('Only MCS HDF5 version 1 is supported!');
            end
            
            % Data structure
            dataAttributes = inf.Groups.Attributes;
            for fni = 1:length(dataAttributes)
                md.Data.(dataAttributes(fni).Name) = dataAttributes(fni).Value;
            end
            
            % Recordings
            for recs = 1:length(inf.Groups)
                md.Recording{recs} = McsHDF5.McsRecording(filename, inf.Groups(recs).Groups);
            end
        end
      
    end
    
end