function version()

    fprintf(['This is version 1.3.1 of the McsHDF5 Matlab toolbox. (08/24/2022)\n'...
        'Newer versions will be available at \n\n'...
        '\thttp://www.multichannelsystems.com/software/multi-channel-datamanager \n'...
        '\thttps://github.com/multichannelsystems/McsMatlabDataTools \n']);

end